name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: enzymeml-linux
            asset_name: enzymeml-linux
          - os: windows-latest
            artifact_name: enzymeml-windows.exe
            asset_name: enzymeml-windows
          - os: macos-latest
            artifact_name: enzymeml-macos
            asset_name: enzymeml-macos
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Install libSBML (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build

      - name: Build binary
        env:
          SCCACHE_GHA_ENABLED: 'true'
          RUSTC_WRAPPER: 'sccache'
        run: |
          cargo build --release --bin enzymeml

      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mv target/release/enzymeml.exe target/release/${{ matrix.artifact_name }}
        continue-on-error: true

      - name: Rename binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mv target/release/enzymeml target/release/${{ matrix.artifact_name }}
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}
          if-no-files-found: warn
